In [1]:
import pandas as pd

%matplotlib inline
# load in the community center data file
data = pd.read_csv("householdincome.csv", index_col="Estimate; Total:", parse_dates=True)

# look at the first ten rows of the data
data.head(10)

,_id,Neighborhood,Id,Margin of Error; Total:,"Estimate; Total: - Less than $10,000","Margin of Error; Total: - Less than $10,000","Estimate; Total: - $10,000 to $14,999","Margin of Error; Total: - $10,000 to $14,999","Estimate; Total: - $15,000 to $19,999","Margin of Error; Total: - $15,000 to $19,999",...,"Estimate; Total: - $75,000 to $99,999","Margin of Error; Total: - $75,000 to $99,999","Estimate; Total: - $100,000 to $124,999","Margin of Error; Total: - $100,000 to $124,999","Estimate; Total: - $125,000 to $149,999","Margin of Error; Total: - $125,000 to $149,999","Estimate; Total: - $150,000 to $199,999","Margin of Error; Total: - $150,000 to $199,999","Estimate; Total: - $200,000 or more","Margin of Error; Total: - $200,000 or more"
Estimate; Total:,,,,,,,,,,,,,,,,,,,,,
870.0,1,Allegheny Center,1,93.000000,147.0,57.000000,115.0,54.000000,30.0,21.000000,...,73.0,39.000000,26.0,18.000000,25.0,25.000000,12.0,17.000000,21.0,21.000000
146.0,2,Allegheny West,2,36.000000,0.0,10.000000,3.0,7.000000,4.0,6.000000,...,11.0,10.000000,20.0,17.000000,0.0,10.000000,9.0,13.000000,21.0,24.000000
1069.0,3,Allentown,3,132.457540,190.0,82.134037,78.0,42.825226,78.0,80.305666,...,36.0,32.015621,31.0,42.941821,14.0,27.856777,0.0,17.320508,3.0,16.248077
701.0,4,Arlington,4,104.465305,70.0,42.497059,35.0,26.870058,56.0,29.086079,...,141.0,54.212545,23.0,17.804494,6.0,16.248077,7.0,17.320508,2.0,15.000000
144.0,5,Arlington Heights,5,59.000000,48.0,42.000000,23.0,27.000000,43.0,52.000000,...,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000
1946.0,6,Banksville,6,229.222599,51.0,43.588989,72.0,75.822160,155.0,83.048179,...,251.0,108.189648,126.0,71.337227,156.0,91.285267,64.0,45.442271,49.0,53.310412
723.0,7,Bedford Dwellings,7,53.000000,307.0,75.000000,129.0,50.000000,91.0,48.000000,...,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000
3567.0,8,Beechview,8,258.027130,269.0,102.547550,136.0,64.822835,244.0,100.064979,...,427.0,114.017543,279.0,102.990291,87.0,50.189640,45.0,40.583248,31.0,36.249138
848.0,9,Beltzhoover,9,156.057682,132.0,88.147603,182.0,95.519631,63.0,44.440972,...,43.0,36.945906,7.0,20.518285,0.0,20.000000,15.0,23.194827,0.0,20.000000
4571.0,10,Bloomfield,10,205.494525,521.0,117.940663,261.0,69.907081,297.0,81.111035,...,519.0,103.754518,168.0,55.488738,155.0,63.898357,125.0,55.865911,108.0,46.925473

In [12]:
import pandas as pd

# Load the CSV file into a DataFrame
file_path = 'householdincome.csv'  # Update with the correct file path
data = pd.read_csv(file_path)  # Assuming the file is comma-separated (CSV)

# Specify the correct column name for the income range
income_column = 'Estimate; Total: - $75,000 to $99,999'

# Select the columns needed for analysis
columns_of_interest = ['Id', 'Neighborhood', income_column]

# Find the 5 neighborhoods with the highest number of households in the income range $75,000 to $99,999
top_5_neighborhoods = data.nlargest(5, income_column)[columns_of_interest]

# Print the top 5 neighborhoods with the respective count of households
print("Top 5 neighborhoods with the most households earning between $75,000 and $99,999:")
print(top_5_neighborhoods)

Top 5 neighborhoods with the most households earning between $75,000 and $99,999:
    Id         Neighborhood  Estimate; Total: - $75,000 to $99,999
77  78  Squirrel Hill South                                  741.0
13  14            Brookline                                  674.0
53  54     Mount Washington                                  604.0
9   10           Bloomfield                                  519.0
68  69            Shadyside                                  508.0

In [14]:
import pandas as pd

# Load the CSV file into a DataFrame
file_path = 'householdincome.csv'  # Update with the correct file path
data = pd.read_csv(file_path)  # Assuming the file is comma-separated (CSV)

# Select the columns needed for analysis
columns_of_interest = ['Id', 'Neighborhood', 'Estimate; Total: - $75,000 to $99,999']

# Find the 5 neighborhoods with the highest number of households in the income range $75,000 to $99,999
top_5_neighborhoods = data.nlargest(5, 'Estimate; Total: - $75,000 to $99,999')[columns_of_interest]

# Print the top 5 neighborhoods with the respective count of households
print("Top 5 neighborhoods with the most households earning between $75,000 and $99,999:")
print(top_5_neighborhoods)

Top 5 neighborhoods with the most households earning between $75,000 and $99,999:
    Id         Neighborhood  Estimate; Total: - $75,000 to $99,999
77  78  Squirrel Hill South                                  741.0
13  14            Brookline                                  674.0
53  54     Mount Washington                                  604.0
9   10           Bloomfield                                  519.0
68  69            Shadyside                                  508.0

In [13]:
# Load the CSV file into a DataFrame
file_path = 'householdincome.csv'  # Update with the correct file path
data = pd.read_csv(file_path)  # Assuming the file is comma-separated (CSV)

# Specify the correct column name for the income range
income_column = 'Estimate; Total: - $200,000 or more'

# Select the columns needed for analysis
columns_of_interest = ['Id', 'Neighborhood', income_column]

# Find the 5 neighborhoods with the highest number of households in the income range $75,000 to $99,999
top_5_neighborhoods = data.nlargest(5, income_column)[columns_of_interest]

# Print the top 5 neighborhoods with the respective count of households
print("Top 5 neighborhoods with the most households earning $200,000 or more':")
print(top_5_neighborhoods)

Top 5 neighborhoods with the most households earning $200,000 or more':
    Id               Neighborhood  Estimate; Total: - $200,000 or more
76  77        Squirrel Hill North                                935.0
77  78        Squirrel Hill South                                821.0
68  69                  Shadyside                                559.0
63  64               Point Breeze                                482.0
16  17  Central Business District                                364.0

In [24]:

import pandas as pd

# Provide the correct file path
file_path = 'householdincome.csv'

# Load the CSV file into a DataFrame
data = pd.read_csv(file_path)

# Now you can access the columns attribute
columns = data.columns
print(columns)

#file_path.columns

Index(['_id', 'Neighborhood', 'Id', 'Estimate; Total:',
       'Margin of Error; Total:', 'Estimate; Total: - Less than $10,000',
       'Margin of Error; Total: - Less than $10,000',
       'Estimate; Total: - $10,000 to $14,999',
       'Margin of Error; Total: - $10,000 to $14,999',
       'Estimate; Total: - $15,000 to $19,999',
       'Margin of Error; Total: - $15,000 to $19,999',
       'Estimate; Total: - $20,000 to $24,999',
       'Margin of Error; Total: - $20,000 to $24,999',
       'Estimate; Total: - $25,000 to $29,999',
       'Margin of Error; Total: - $25,000 to $29,999',
       'Estimate; Total: - $30,000 to $34,999',
       'Margin of Error; Total: - $30,000 to $34,999',
       'Estimate; Total: - $35,000 to $39,999',
       'Margin of Error; Total: - $35,000 to $39,999',
       'Estimate; Total: - $40,000 to $44,999',
       'Margin of Error; Total: - $40,000 to $44,999',
       'Estimate; Total: - $45,000 to $49,999',
       'Margin of Error; Total: - $45,000 to $49,999',
       'Estimate; Total: - $50,000 to $59,999',
       'Margin of Error; Total: - $50,000 to $59,999',
       'Estimate; Total: - $60,000 to $74,999',
       'Margin of Error; Total: - $60,000 to $74,999',
       'Estimate; Total: - $75,000 to $99,999',
       'Margin of Error; Total: - $75,000 to $99,999',
       'Estimate; Total: - $100,000 to $124,999',
       'Margin of Error; Total: - $100,000 to $124,999',
       'Estimate; Total: - $125,000 to $149,999',
       'Margin of Error; Total: - $125,000 to $149,999',
       'Estimate; Total: - $150,000 to $199,999',
       'Margin of Error; Total: - $150,000 to $199,999',
       'Estimate; Total: - $200,000 or more',
       'Margin of Error; Total: - $200,000 or more'],
      dtype='object')